# Generated by Django 3.0.3 on 2020-03-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreeAgentBackEnd_app', '0002_remove_cuota_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='equipo',
            field=models.ForeignKey(on_delete=models.SET(0), to='FreeAgentBackEnd_app.Equipo'),
        ),
    ]
