# Generated by Django 3.0.3 on 2020-03-11 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FreeAgentBackEnd_app', '0003_auto_20200311_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='equipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FreeAgentBackEnd_app.Equipo'),
        ),
    ]
