# Generated by Django 3.0.3 on 2020-03-29 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreeAgentBackEnd_app', '0004_auto_20200311_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuota',
            name='renovacion_automatica',
            field=models.BooleanField(),
        ),
    ]
